apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lnd.name" . }}
  labels:
    app: {{ template "lnd.name" . }}
    chart: {{ template "lnd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ if eq .Values.bitcoin.node "bitcoind" }}
  test: test
  {{ end }}