apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "lnd.name" . }}
  labels:
    app: {{ template "lnd.name" . }}
    chart: {{ template "lnd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
spec:
  revisionHistoryLimit: {{ .Values.lnd.revisionHistoryLimit }}
  replicas: {{ .Values.lnd.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "lnd.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "lnd.name" . }}
        release: {{ .Release.Name }}
    spec:
      #securityContext:
      #  runAsUser: 1000
      #  runAsGroup: 1000
      #  fsGroup: 1000
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: init-wallet
        {{ if (( .Values.lndinit).digest) }}
        image: "{{ .Values.lndinit.repository }}@{{ .Values.lndinit.digest }}"
        {{ else }}
        image: "{{ .Values.lndinit.repository }}:{{ .Values.lndinit.tag }}"
        {{ end }}
        command: ['/bin/bash']
        args: ['/root/init-wallet.sh']
        volumeMounts:
          - name: init-wallet
            mountPath: /root/init-wallet.sh
            subPath: init-wallet.sh
          - name: secrets
            mountPath: /root/.lnd/unlock.secret
            subPath: autoUnlockPassword
          - name: data
            mountPath: /root/.lnd/
      containers:
        - name: {{ template "lnd.fullname" . }}
          {{ if ((.Values.image).digest) }}
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
          {{ else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{ end }}
          command: ["lnd"]
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          resources:
            requests:
              cpu: 250m
              memory: 1G
            limits:
              cpu: 250m
              memory: 1G
          env:
            - name: CHECKSUM
              value: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
            - name: RPCPASS
              valueFrom:
                secretKeyRef:
                  key: rpcpassword
                  name: {{ template "lnd.name" . }}
            - name: RPCUSER
              valueFrom:
                secretKeyRef:
                  key: rpcuser
                  name: {{ template "lnd.name" . }}
          ports:
            - name: rpc
              containerPort: 10009
            - name: rest
              containerPort: 8080
            - name: p2p
              containerPort: 9735
            - name: letsencrypt
              containerPort: 8088
            - name: watchtower
              containerPort: 9911
          volumeMounts:
            - name: data
              mountPath: /root/.lnd/
            - name: configmap
              mountPath: /root/.lnd/lnd.conf
              subPath: lnd.conf
            - name: secrets
              mountPath: /root/.lnd/unlock.secret
              subPath: autoUnlockPassword
          lifecycle:
            preStop:
              exec:
                # Make sure we safely quit lnd so we don't corrupt anything
                command: ["/bin/lncli", "-n", "{{ .Values.network }}", "stop"]
      volumes:
        - name: secrets
          secret:
            secretName: {{ template "lnd.name" . }}
        - name: configmap
          configMap:
            name: {{ template "lnd.name" . }}
        - name: init-wallet
          configMap:
            name: init-wallet-script
            defaultMode: 0777
        - name: data
          persistentVolumeClaim:
            claimName: {{ template "lnd.name" . }}