apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "lnd.name" . }}
  labels:
    app: {{ template "lnd.name" . }}
    chart: {{ template "lnd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if .Release.IsInstall }}
  autoUnlockPassword: {{ randAlphaNum (.Values.application.autoUnlockPasswordLength | int) | b64enc }}
  {{ else }}
  autoUnlockPassword: {{ index (lookup "v1" "Secret" .Release.Namespace "lnd").data "autoUnlockPassword" }}
  {{ end }}
