apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ template "lnd.name" . }}
  labels:
    app: {{ template "lnd.name" . }}
    chart: {{ template "lnd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if .Release.IsInstall }}
  autoUnlockPassword: {{ randAlphaNum (.Values.application.autoUnlockPasswordLength | int) | b64enc }}
  {{ else }}
  autoUnlockPassword: {{ index (lookup "v1" "Secret" .Release.Namespace "lnd").data "autoUnlockPassword" }}
  {{ end }}
  {{ if eq .Values.bitcoin.node "bitcoind" }}
  {{- if (lookup "v1" "Secret" .Values.bitcoin.bitcoind.namespace "bitcoind") }}
  rpcuser: {{ index (lookup "v1" "Secret" .Values.bitcoin.bitcoind.namespace "bitcoind").data "rpcuser" }} #Username for RPC connections to bitcoind. By default, lnd will attempt to automatically obtain the credentials, so this likely won't need to be set (other than for a remote bitcoind instance).
  rpcpassword: {{ index (lookup "v1" "Secret" .Values.bitcoin.bitcoind.namespace "bitcoind").data "rpcpassword" }} #Password for RPC connections to bitcoind. By default, lnd will attempt to automatically obtain the credentials, so this likely won't need to be set (other than for a remote bitcoind instance).
  {{ else }}
  rpcuser: "default"
  rpcpassword: "default"
  {{- end }}
  {{ end }}
