apiVersion: v1
kind: Service
metadata:
  name: {{ template "lnd.fullname" . }}-internal
  labels:
    app: {{ template "lnd.name" . }}
    chart: {{ template "lnd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: rpc
      port: {{ .Values.internalServices.rpcPort }}
      targetPort: rpc
    - name: rest
      port: {{ .Values.internalServices.restPort }}
      targetPort: rest
  selector:
    app: {{ template "lnd.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "lnd.fullname" . }}-external
  labels:
    app: {{ template "lnd.name" . }}
    chart: {{ template "lnd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.externalServices.externalIp }}
spec:
  type: LoadBalancer
  ports:
    - name: p2p
      port: {{ .Values.externalServices.p2pPort }}
      targetPort: p2p
    - name: letsencrypt
      port: {{ .Values.externalServices.letsencryptPort }}
      targetPort: letsencrypt
    - name: watchtower
      port: {{ .Values.externalServices.watchtowerPort }}
      targetPort: watchtower
  selector:
    app: {{ template "lnd.name" . }}
    release: {{ .Release.Name }}
