name: Release Charts

on:
  push:
    branches:
      - 'master'

env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.0

      - name: Run Datree Policy Check
        uses: datreeio/action-datree@main
        with:
          path: 'chart/lnd'
          cliArguments: '-o sarif'
          isHelmChart: true
          helmArguments: '--values chart/lnd/values.yaml'

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: datree.sarif
          wait-for-processing: true

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: chart
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
